name: CI
on: [push, pull_request]
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install -y cc65 libsdl2-dev libsdl2-ttf-dev fonts-dejavu-core libc6-i386 unzip
      - run: make debug
      - run: make sanitize
      - run: make test-functional
      - run: make test-decimal
      - run: make test-interrupt
      - run: make test-apple1
      - run: make test-nestest
      - run: make test-vectors
      - run: make games/snake.bin bin/mos6502-sdl bin/nes
